#!/bin/bash

# expects a /mnt/registry/data directory
# and a /mnt/registry/auth/authfile
# generated by htpasswd -Bbn $USER $PASSWORD /mnt/registry/auth/authfile

set -ex

sudo cp registry.service /etc/systemd/system/registry.service
sudo chmod 644 /etc/systemd/system/registry.service
sudo systemctl daemon-reload
sudo systemctl enable registry.service
sudo systemctl restart registry
#sudo systemctl status
sudo journalctl -fu registry.service

